# listener
datafolder: '/home/flo/Nextcloud/data/mws/sub'  # '/home/jeff/Nextcloud/data/mws/sub'
region_name: None  # 'eu-central-1'
queuename: None  # 'mwslisten'

# parser
region: None  # one of: CA, US, DE, ES, FR, IN, IT, UK, JP, CN, MX
ownsellerid: None
currencycode: None  # 'EUR'

# update prices, mws credentials
access_key: None
secret_key: None
account_id: None
